name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:  # Manual triggering event
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable Corepack before setting up Node
        run: corepack enable
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21.5.0

      - name: Install dependencies
        run: yarn install

      - name: Build for production
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
